### PR TITLE
portability(gcc and clang agnostic)

### PR DESCRIPTION
**Pull request by pepper-jelly**
building with `make CC=clang` complaints about missing newline at the end of file

### CODE REVIEW

**Comment by pepper-jelly** [comment]
Also ##__VA_ARGS__ is a GNU specific macro

**Comment by bakkeby** [comment]
Thanks, I see no reason not to take these changes.

Out of interest was the command you ran this?
```
sed -i -e '$a\' <file>
```

**Comment by pepper-jelly** [comment]
`'$a\'` supposed to add \n if there no trailing \n but didn't worked.  Simply:
```bash
#to overview last 2 lines
for n in `ls`; do echo -n ------ $n ------; tail -n2 $n; done
#add new line
for n in `ls`; do echo >> $n; done
```

**Comment by bakkeby** [comment]
Thanks for that.

**Comment by pepper-jelly** [comment]
It's nothing. Thanks to you for convenient dwm.

**Pull request merged**
