### PR TITLE
focusfollowmouseonkill patch and a barborder fix

### PR DESCRIPTION
**Pull request by Randomguy-8**

### CODE REVIEW

**Comment by bakkeby** [comment]
What you have here are two separate change sets and they should really be split into two separate pull requests.

The reason for this, as you will see, is that there will be two different discussions and if they remain together then one change can not go forward without the other.

----

The barborder fix:
https://github.com/bakkeby/dwm-flexipatch/pull/364/commits/c4b393e944d8a256e5fcfd07a71a7570d09f24f7
https://github.com/bakkeby/dwm-flexipatch/pull/364/commits/8b3c53a8e1c15da29f151bb5d6402914a43984a7

Exposing the bar border size as a configuration option is in principle fine.

There are three reasons why this has not already been done:
   - it will break the configuration for someone who uses the bar border patch and updates dwm-flexipatch and
   - a mismatch between the bar border size and the client border size generally do not look good and
   - it is relatively easy for someone to add manually should they really need it

That doesn't mean that we can't include it.

If we do then we would have to reconsider the behaviour when using `setborderpx`. Currently it follows whatever the monitor and clients is set to.

https://github.com/bakkeby/dwm-flexipatch/blob/3881ad4ad14576417cbca3cff4ab852b323089f5/patch/setborderpx.c#L18-L21

As for the config it may be better to set this to `borderpx` rather than 1.

Alternatively one may think of `barborderpx` as an override rather than a plain value. I.e. let the default value of `barborderpx` be 0 and only use it if it is not 0.

By that I mean rather than:

```c
bar->borderpx = barborderpx;
```

you could have:

```c
bar->borderpx = (barborderpx ? barborderpx : borderpx);
```

That way in `setborderpx` for example you can decide whether or not to update the bar border based on the value of `barborderpx`.

----

The focusfollowmouseonkill patch:
https://github.com/bakkeby/dwm-flexipatch/pull/364/commits/6aeca56a225ac2c7c3999706170dca65c52534d3
https://github.com/bakkeby/dwm-flexipatch/pull/364/commits/e2dbcadc02590adbc5de995cdeaf0098f3a93b53

In general I would have a few nitpicks that are very easy to address (indentation, variables declared at the start, boring things like that).

It is more iteresting to talk about what the patch does and how it works.

This being the crucial line grabbing the window the mouse cursor rests on.

```c
XQueryPointer(dpy, root, &root, &child, &rootx, &rooty, &winx, &winy, &mask);
```

I find it a bit strange how we allow the root variable to be overwritten here. [XQueryPointer](https://tronche.com/gui/x/xlib/window-information/XQueryPointer.html) states that it will return the root window that the pointer is logically on. I don't know if it is at all possible for the returned root window to be different to the root window we already have for the display.

This call comes after `XKillClient` and after `XSync`. The window being killed will most likely no longer be there at the time when `XQueryPointer` is called, but there is no guarantee of course.

The application may send a mapping request for a dialog box asking whether you would like to save your document before exiting - but the event for that won't be processed until after we exit the `killclient` function.

It is worth noting that this patch is only effective when using many overlapping floating windows, because for killed tiled windows the mouse pointer will just rest on the the empty background / root window. The description in patches.def.h kind of says it but not explicitly.

It _may_ be possible to achieve something similar for tiled windows, but you would have to do that in the `unmanage` function instead after the client has been removed.

https://github.com/bakkeby/dwm-flexipatch/blob/3881ad4ad14576417cbca3cff4ab852b323089f5/dwm.c#L4459C2-L4461

You would want to do the arrange first, then check what window is underneath the mouse cursor. Possibly one may need to skip enter notify events but one can come back to that.

I am saying this because someone reading the name of this patch may have certain expectations with regards to how it would work, and maybe the patch is better placed in `unmanage` rather than `killclient`.

**Comment by Randomguy-8** [comment]
> What you have here are two separate change sets and they should really be split into two separate pull requests.

Well Sorry for that. (but lets just continue discussion for both 'cause i know both of the patches are important and will eventually be merged)
So as you stated:
> it will break the configuration for someone who uses the bar border patch and updates dwm-flexipatch and

Well that's quite an issue but if someone is updating the dwm-flexipatch, then they must examine all the relevant changes done to it right?
> a mismatch between the bar border size and the client border size generally do not look good and

You can't say quite for sure? As in my case i do want to configure bar border and color separately so that i can make my bar looks alike [chadwm's](https://github.com/siduck/chadwm/blob/screenshots/screenshots/col_layout.png) but doing so will make my bar and client border width as equal(i want barborderwidth > borderwidth). There also might me more use-cases for this.
> it is relatively easy for someone to add manually should they really need it

Not for non-programmer(wasn't for me back then).

Your have more knowledge of X and dwm, so i will go along as you might prefer like setting the default value of barborderpx to 0 and using ```bar->borderpx = (barborderpx ? barborderpx : borderpx);``` instead.

Same goes for focusfollowmouseonkill patch. Read [this](https://www.reddit.com/r/suckless/comments/jfgia5/dwm_quitting_a_window_which_window_gets_focused/). I am not alone, there are others who cant figure the default focusing behavior of dwm or can't remember the last focused window. Thus creating a focusing mess(and sometimes we even kill the wrong client).

This patch is obviously for more mouse driven users and It just insures that whenever a client is kill by user they don't get confused which window is going to be focused next. It will be always the one below mouse.
>I don't know if it is at all possible for the returned root window to be different to the root window we already have for the display.

In dwm's case it is not possible but lets just skip that parts its alright(its always gonna return the root window).

All Last: I will fix few things here and there as you preferred and if there something still remains, please do it.
ThankYou.

**Comment by bakkeby** [comment]
> but lets just continue discussion for both 'cause i know both of the patches are important and will eventually be merged

That is rather presumptuous and arrogant and can easily have the opposite effect of what you are trying to achieve.

> Read [this](https://www.reddit.com/r/suckless/comments/jfgia5/dwm_quitting_a_window_which_window_gets_focused/). I am not alone

I did see that reddit post back in October 2020 when it was posted and you are indeed not alone. For as long as I have been in this game you are the second person to complain about this.

That is not to say that the idea is bad or that not a lot of people would use this. If it makes things more intuitive then it could even become popular. 

> In dwm's case it is not possible but lets just skip that parts its alright(its always gonna return the root window).

That is fine. I suppose what I mean with this is that when someone reads the code then it is a bit unclear what the intent is, like why fetch the root window for the root window if we do not expect this to change. If you look at the `getrootptr` function for example it uses dummy variables to indicate that we are not actually interested in the return values for these fields, but we have to provide them because `XQueryPointer` expects the arguments. Same with `getatomprop`.

> This patch is obviously for more mouse driven users and It just insures that whenever a client is kill by user they don't get confused which window is going to be focused next. It will be always the one below mouse.

Moving the logic to `unmanage` makes this work as intended both when using `killclient` and when closing the window otherwise (e.g. `Ctrl+d` in a terminal).

The change made in https://github.com/bakkeby/dwm-flexipatch/pull/364/commits/d86acaf89fc379d4b880c8d889c1281e26b32e68 will work but you may have a border flicker as `focus` is called on line 4469 and again on line 4471.

In this particular case you would just call `focus(c);` regardless of whether `c` is null or not and get rid of the focus on line 4469.

That said, as a mouse oriented user would it not be much more intuitive if this was the behaviour _all_ the time and not only when a window closes?

I mean you can move the selected client to another tag (or another monitor) and you would have the focus going to a window that is not under the mouse.

Likewise when changing tags (using keybindings), would it not be more intuitive if the window that rests under the mouse pointer would get focus rather than the window that last had focus on that tag?

This can be achieved by defaulting to the client under the mouse pointer if NULL is passed to the `focus` function.

I pushed a prototype patch for this up at:
https://github.com/bakkeby/patches/blob/master/dwm/dwm-focusfollowmouse-6.4.diff

It is pretty simple just that all the `focus(NULL);` calls need to be moved below the arrange. If the user moves the mouse cursor on top of the bar then it will behave like normal, giving focus to the most recently focused client that is visible.

**Comment by bakkeby** [comment]
I integrated the bar border fix and focusfollowmouse patch separately so I will close this PR.

**Pull request closed without merging**
